
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ruhan
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */

    DatabaseConnection db;
    Statement st;

    public Settings() {
        db=new DatabaseConnection();
        st=db.getDbStatement();
        initComponents();
        this.setLocationRelativeTo(null);
        refresh();
        refresh1();
        refresh2();
        usericon();
    }
    
    public void usericon(){
        String s="";
        try{

                    ResultSet rs=st.executeQuery("select *from userselection");
           
                    
           
                    while(rs.next()){
                        String s1=rs.getString("user");
                        s=s1;
               
                       
                    }
           
                }catch(Exception e){
            
                 }
        icon.setText("  Hello, "+s+"!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        musertable = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        searchtxt = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        box = new javax.swing.JComboBox<>();
        jButton12 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        pac = new javax.swing.JPasswordField();
        jSeparator10 = new javax.swing.JSeparator();
        nac = new javax.swing.JPasswordField();
        jSeparator11 = new javax.swing.JSeparator();
        cac = new javax.swing.JPasswordField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1214, 712));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 20, 60, 50);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homex24.png"))); // NOI18N
        jButton2.setText("           Home");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 110, 270, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 150, 270, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 220, 270, 30);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 290, 270, 30);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(0, 358, 270, 30);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(0, 430, 270, 30);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(0, 500, 270, 20);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(0, 570, 270, 30);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(0, 640, 270, 30);
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(0, 710, 270, 10);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardx24.png"))); // NOI18N
        jButton3.setText("     Dashboard");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 180, 270, 40);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profilex24.png"))); // NOI18N
        jButton4.setText("           Profile");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 250, 270, 40);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/requestsx24.png"))); // NOI18N
        jButton5.setText("        Requests");
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(0, 320, 270, 40);

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donorlistx24.png"))); // NOI18N
        jButton6.setText("      Donor List");
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(0, 393, 270, 40);

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adddonorx24.png"))); // NOI18N
        jButton7.setText("     Add Donor");
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(0, 460, 270, 40);

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Requestforbloodgeneralx24.png"))); // NOI18N
        jButton8.setText(" Blood Request");
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(0, 530, 270, 40);

        jButton9.setBackground(new java.awt.Color(102, 102, 102));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settingsx24.png"))); // NOI18N
        jButton9.setText("        Settings");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(0, 600, 270, 40);

        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exitx24.png"))); // NOI18N
        jButton10.setText("        Exit");
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(0, 670, 270, 40);

        jTabbedPane4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(null);

        musertable.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        musertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Users"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        musertable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(musertable);
        if (musertable.getColumnModel().getColumnCount() > 0) {
            musertable.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(60, 10, 180, 500);

        jButton14.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x-button.png"))); // NOI18N
        jButton14.setText("  Remove");
        jButton14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton14.setContentAreaFilled(false);
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(570, 240, 160, 50);

        jTabbedPane4.addTab("Manage Users", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(null);

        jPanel5.setLayout(null);

        jPanel11.setBackground(new java.awt.Color(204, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Remove Requests", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel11.setLayout(null);

        table.setBackground(new java.awt.Color(255, 204, 204));
        table.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Name", "Blood Group", "Address", "Contact 01", "Contact 02"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel11.add(jScrollPane2);
        jScrollPane2.setBounds(10, 50, 910, 360);

        jButton13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x-button.png"))); // NOI18N
        jButton13.setText("   Remove");
        jButton13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton13.setContentAreaFilled(false);
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jPanel11.add(jButton13);
        jButton13.setBounds(380, 440, 190, 50);

        jPanel5.add(jPanel11);
        jPanel11.setBounds(0, 0, 930, 520);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 0, 930, 530);

        jTabbedPane4.addTab("Manage Requests", jPanel2);

        jPanel3.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Remove Donors", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel9.setLayout(null);

        table1.setBackground(new java.awt.Color(255, 204, 204));
        table1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donor  ID", "Name", "Age", "Gender", "Blood Group", "ID", "Address", "Contact", "Added by"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(0).setResizable(false);
            table1.getColumnModel().getColumn(1).setResizable(false);
            table1.getColumnModel().getColumn(2).setResizable(false);
            table1.getColumnModel().getColumn(3).setResizable(false);
            table1.getColumnModel().getColumn(4).setResizable(false);
            table1.getColumnModel().getColumn(5).setResizable(false);
            table1.getColumnModel().getColumn(6).setResizable(false);
            table1.getColumnModel().getColumn(7).setResizable(false);
            table1.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel9.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 910, 210);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magnifying-glass.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton1);
        jButton1.setBounds(820, 40, 100, 50);

        searchtxt.setBackground(new java.awt.Color(255, 204, 204));
        searchtxt.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        searchtxt.setForeground(new java.awt.Color(0, 0, 204));
        searchtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchtxt.setBorder(null);
        searchtxt.setOpaque(false);
        jPanel9.add(searchtxt);
        searchtxt.setBounds(430, 50, 230, 30);
        jPanel9.add(jSeparator14);
        jSeparator14.setBounds(430, 80, 230, 10);

        box.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Search by-", "Blood Group", "Name", "Donor ID" }));
        jPanel9.add(box);
        box.setBounds(680, 50, 130, 30);

        jButton12.setBackground(new java.awt.Color(255, 102, 0));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x-button.png"))); // NOI18N
        jButton12.setText("   Remove");
        jButton12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton12.setContentAreaFilled(false);
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton12);
        jButton12.setBounds(440, 420, 160, 50);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(0, 0, 940, 520);

        jTabbedPane4.addTab("Manage Donors", jPanel3);

        jPanel4.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel6.setLayout(null);

        pac.setBackground(new java.awt.Color(204, 255, 255));
        pac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pac.setBorder(null);
        jPanel6.add(pac);
        pac.setBounds(500, 90, 190, 30);
        jPanel6.add(jSeparator10);
        jSeparator10.setBounds(500, 120, 190, 10);

        nac.setBackground(new java.awt.Color(204, 255, 255));
        nac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nac.setBorder(null);
        jPanel6.add(nac);
        nac.setBounds(500, 170, 190, 30);
        jPanel6.add(jSeparator11);
        jSeparator11.setBounds(500, 200, 190, 10);

        cac.setBackground(new java.awt.Color(204, 255, 255));
        cac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cac.setBorder(null);
        jPanel6.add(cac);
        cac.setBounds(500, 250, 190, 30);
        jPanel6.add(jSeparator12);
        jSeparator12.setBounds(500, 280, 190, 10);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Confirm Admin Approval Code          :");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(220, 250, 260, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Previous Admin Approval Code         :");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(220, 90, 260, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("New Admin Approval Code                :");
        jPanel6.add(jLabel10);
        jLabel10.setBounds(220, 170, 260, 30);

        jButton11.setBackground(new java.awt.Color(255, 102, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        jButton11.setText("   Update");
        jButton11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton11.setContentAreaFilled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11);
        jButton11.setBounds(400, 420, 160, 50);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(0, 0, 940, 520);

        jTabbedPane4.addTab("Update Admin approval code", jPanel4);

        jPanel7.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));
        jPanel8.setLayout(null);
        jPanel8.add(jPanel10);
        jPanel10.setBounds(0, 0, 10, 10);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(0, 0, 930, 520);

        jTabbedPane4.addTab("Reports", jPanel7);

        getContentPane().add(jTabbedPane4);
        jTabbedPane4.setBounds(280, 160, 930, 550);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Donate blood and save life!");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(830, 140, 140, 13);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel6.setText("Blood Donor Management System");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(560, 100, 400, 30);

        icon.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        icon.setForeground(new java.awt.Color(153, 153, 0));
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boy (1).png"))); // NOI18N
        getContentPane().add(icon);
        icon.setBounds(1044, 134, 160, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Daffodil International University");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 60, 260, 40);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s006_LightBlue.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 460, 270, 460);

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s006_LightBlue.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 270, 480);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s006_LightBlue.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 0, 800, 180);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s006_LightBlue.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1060, 0, 160, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int check=JOptionPane.showConfirmDialog(null,"YES     for     Exit\nNO       for    ReLogin ","Choose one...",JOptionPane.YES_NO_OPTION);
        if(check==0){
            //code suru
            String update="UPDATE `settings` SET `sure`='1' WHERE 1";
            executeSQLQuery(update);
            
            String update2="UPDATE `userselection` SET `user`='Open' WHERE 1";
            executeSQLQuery(update2);
            
            //code sesh
            System.exit(0);
        }
        if(check==1){
            String update="UPDATE `settings` SET `sure`='1' WHERE 1";
            executeSQLQuery(update);
            
            String update2="UPDATE `userselection` SET `user`='Open' WHERE 1";
            executeSQLQuery(update2);
            
            login l=new login();
            close();
            l.setVisible(true);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    
    private void executeSQLQuery(String query) {
       try{

          
           if(st.executeUpdate(query)==1){
              // JOptionPane.showMessageDialog(null,"","Congrats..",JOptionPane.INFORMATION_MESSAGE);
               
//ys/no code hbe
           }else{
               //JOptionPane.showMessageDialog(null,"Registration Unsuccessful!!","Sorry!",JOptionPane.WARNING_MESSAGE); 
           }
           
           
       }catch(Exception e){
            
       }
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Home h=new Home();
        close();
        h.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Dashboard d=new Dashboard();
        close();
       d.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        close();
        Profile bg=new Profile();
        bg.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Requests ad=new Requests();
        close();
        ad.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DonorList dl=new DonorList();
        close();
        dl.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       boolean b=false;
        
        //code suru
        try{

                    ResultSet rs=st.executeQuery("select *from settings");
           
                    
           
                    while(rs.next()){
                        String s1=rs.getString("sure");
                        if(s1.equals("2")){
                            b=true;
                        }
               
                       
                    }
           
                }catch(Exception e){
            
                 }
        
        //code sesh
        
        if(b==true){
            AddDonor ad=new AddDonor();
             ad.setVisible(true);
             close();
        }else{
            JOptionPane.showMessageDialog(this,"This Option is Admin Property!");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        BloodRequest br=new BloodRequest();
        close();
        br.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String pre=pac.getText();
        String nc=nac.getText();
        String cnc=cac.getText();
        
        if(pre.equals("") || nc.equals("") || cnc.equals("")){
            JOptionPane.showMessageDialog(null,"Please fill up all Field.","Alert",JOptionPane.WARNING_MESSAGE);
        }else{
            if(nc.length()<5){
                JOptionPane.showMessageDialog(null,"Approval Code length must be grater then 4!","Alert",JOptionPane.WARNING_MESSAGE);
            }else{
                boolean check=false;
                try{

                    ResultSet rs=st.executeQuery("select *from admin");
           
                    
           
                    while(rs.next()){
                        String s1=rs.getString("key");
                        if(s1.equals(pre)){
                            check=true;
                        }
               
                       
                    }
           
                }catch(Exception e){
            
                 }
                
                if(check==true){
                    if(nac.getText().equals(cac.getText())){
                        JOptionPane.showMessageDialog(null,"Successfully Updated Admin Approval code.","Congrats!",JOptionPane.INFORMATION_MESSAGE);
                        String update="UPDATE `admin` SET `key`='"+nac.getText()+"' WHERE 1";
                        executeSQLQuery(update);
                        pac.setText("");
                        nac.setText("");
                        cac.setText("");
                    }else{
                        JOptionPane.showMessageDialog(null,"Check Confirm Approval Code.","Alert",JOptionPane.WARNING_MESSAGE);
                    }
                    
                }else{
                     JOptionPane.showMessageDialog(null,"Previous Admin Approval is not Correct.","Alert",JOptionPane.WARNING_MESSAGE);
 
                }
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String search=searchtxt.getText();
        
        String opt=box.getSelectedItem().toString();
        
        if(opt.equals("-Search by-")){
            
            DefaultTableModel model=(DefaultTableModel) table1.getModel();
            model.setRowCount(0);
            
            refresh();
        }
        else if(opt.equals("Blood Group")){
            DefaultTableModel model=(DefaultTableModel) table1.getModel();
            model.setRowCount(0);
            bg();
        }
        
        else if(opt.equals("Name")){
           
            DefaultTableModel model=(DefaultTableModel) table1.getModel();
            model.setRowCount(0);
            
            name();
        }
        
        else if(opt.equals("Donor ID")){
            DefaultTableModel model=(DefaultTableModel) table1.getModel();
            model.setRowCount(0);
            id();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        int i=table1.getSelectedRow();
        
        TableModel model=table1.getModel();
        
        String s=model.getValueAt(i, 0).toString();
        
        String delete="DELETE FROM `donors` WHERE DonorId= "+s;
        executeSQLQuery(delete);
        
        DefaultTableModel m=(DefaultTableModel) table1.getModel();
        m.setRowCount(0);
        refresh();
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        int i=table.getSelectedRow();
        
        TableModel model=table.getModel();
        
        String s=model.getValueAt(i, 0).toString();
        
        String delete="DELETE FROM `requests` WHERE requestId= "+s;
        executeSQLQuery(delete);
        
        DefaultTableModel m=(DefaultTableModel) table.getModel();
        m.setRowCount(0);
        refresh1();
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        int i=musertable.getSelectedRow();
        
        TableModel model=musertable.getModel();
        
        String s=model.getValueAt(i, 0).toString();
        
        String delete="DELETE FROM `user` WHERE Username= '"+model.getValueAt(i, 0).toString()+"'";
        executeSQLQuery(delete);
        
        String d=s;
        
            String delete1="DELETE FROM `donors` WHERE Added by=\""+d+"\"";
            executeSQLQuery(delete1);
        
            String delete2="DELETE FROM `requests` WHERE Request by=\""+d+"\"";
            executeSQLQuery(delete2);
        
            //String delete3="DELETE FROM `user` WHERE Username=\""+d+"\"";
             //executeSQLQuery(delete3);
        
            String delet="DELETE FROM `userprofile` WHERE Un=\""+d+"\"";
        
            executeSQLQuery(delet);
            
            String db="DROP DATABASE "+d;
            
            
            try{

                CustomDatabaseConnection cdb=new CustomDatabaseConnection("");
                Statement st= cdb.getDbStatement();
           
                st.executeUpdate(db);
           
            }catch(Exception e){
            
            }
        
        
        
        
        DefaultTableModel m=(DefaultTableModel) musertable.getModel();
        m.setRowCount(0);
        refresh2();
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        boolean b=false;
        
        //code suru
        try{

                    ResultSet rs=st.executeQuery("select *from settings");
           
                    
           
                    while(rs.next()){
                        String s1=rs.getString("sure");
                        if(s1.equals("2")){
                            b=true;
                        }
               
                       
                    }
           
                }catch(Exception e){
            
                 }
        
        //code sesh
        
        if(b==true){
            BloodRequest br=new BloodRequest();
        
            br.setVisible(true);
            close();
        }else{
            JOptionPane.showMessageDialog(this,"This Option is Admin Property!");
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    
    public void refresh2(){
        try{

           ResultSet rs=st.executeQuery("select *from user");
           
           DefaultTableModel model=(DefaultTableModel) musertable.getModel();
           Object rowData[]=new Object[1];
           while(rs.next()){
               String s1=rs.getString("Username");
               
               rowData[0]=s1;
               
               model.addRow(rowData);
           }
           
       }catch(Exception e){
            
       }
    }
    
    
    
    
    
    
    
    
    
    
    
    public void refresh1(){
        try{

           ResultSet rs=st.executeQuery("select *from requests");
           
           DefaultTableModel model=(DefaultTableModel) table.getModel();
           Object rowData[]=new Object[6];
           while(rs.next()){
               String s1=rs.getString("requestId");
               String s2=rs.getString("Name");
               String s3=rs.getString("Address");
               String s4=rs.getString("Bg");
               String s5=rs.getString("Contact1");
               String s6=rs.getString("Contact2");
               
               rowData[0]=s1;
               rowData[1]=s2;
               rowData[2]=s4;
               rowData[3]=s3;
               rowData[4]=s5;
               rowData[5]=s6;
               
               model.addRow(rowData);
           }
           
       }catch(Exception e){
            
       }
    }
    
    
    
    
    
    
    
    
    
    public void id(){
        try{

           ResultSet rs=st.executeQuery("select *from donors");
           
           DefaultTableModel model=(DefaultTableModel) table1.getModel();
           Object rowData[]=new Object[9];
           String search=searchtxt.getText();
           while(rs.next()){
               
               String s1=rs.getString("DonorId");
               
               
               
               if(search.equalsIgnoreCase(s1)){
                   
               String s2=rs.getString("Name");
               String s3=rs.getString("Age");
               String s4=rs.getString("Gender");
               String s5=rs.getString("Bg");
               String s6=rs.getString("Id");
               String s7=rs.getString("Address");
               String s8=rs.getString("Contact");
               String s9=rs.getString("Added by");
                    rowData[0]=s1;
                    rowData[1]=s2;
                    rowData[2]=s3;
                    rowData[3]=s4;
                    rowData[4]=s5;
                    rowData[5]=s6;
                    rowData[6]=s7;
                    rowData[7]=s8;
                    rowData[8]=s9;
               
                    model.addRow(rowData);  
               }
               
               
               
           }
           
       }catch(Exception e){
            
       }
    }
    
    
    //name
    public void name(){
        try{

           ResultSet rs=st.executeQuery("select *from donors");
           
           DefaultTableModel model=(DefaultTableModel) table1.getModel();
           Object rowData[]=new Object[9];
           while(rs.next()){
               String s1=rs.getString("DonorId");
               String s2=rs.getString("Name");
               String s3=rs.getString("Age");
               String s4=rs.getString("Gender");
               String s5=rs.getString("Bg");
               String s6=rs.getString("Id");
               String s7=rs.getString("Address");
               String s8=rs.getString("Contact");
               String s9=rs.getString("Added by");
               
               
               String search=searchtxt.getText();
               
               if(search.equalsIgnoreCase(s2)){
                    rowData[0]=s1;
                    rowData[1]=s2;
                    rowData[2]=s3;
                    rowData[3]=s4;
                    rowData[4]=s5;
                    rowData[5]=s6;
                    rowData[6]=s7;
                    rowData[7]=s8;
                    rowData[8]=s9;
               
                    model.addRow(rowData);  
               }
               
               
               
           }
           
       }catch(Exception e){
            
       }
    }
    
    
    //bg
    public void bg(){
        try{

           ResultSet rs=st.executeQuery("select *from donors");
           
           DefaultTableModel model=(DefaultTableModel) table1.getModel();
           Object rowData[]=new Object[9];
           while(rs.next()){
               String s1=rs.getString("DonorId");
               String s2=rs.getString("Name");
               String s3=rs.getString("Age");
               String s4=rs.getString("Gender");
               String s5=rs.getString("Bg");
               String s6=rs.getString("Id");
               String s7=rs.getString("Address");
               String s8=rs.getString("Contact");
               String s9=rs.getString("Added by");
               
               
               String search=searchtxt.getText();
               
               if(search.equalsIgnoreCase(s5)){
                    rowData[0]=s1;
                    rowData[1]=s2;
                    rowData[2]=s3;
                    rowData[3]=s4;
                    rowData[4]=s5;
                    rowData[5]=s6;
                    rowData[6]=s7;
                    rowData[7]=s8;
                    rowData[8]=s9;
               
                    model.addRow(rowData);  
               }
               
               
               
           }
           
       }catch(Exception e){
            
       }
    }
    
    
    
    // refresh
    public void refresh(){
        try{

           ResultSet rs=st.executeQuery("select *from donors");
           
           DefaultTableModel model=(DefaultTableModel) table1.getModel();
           Object rowData[]=new Object[9];
           while(rs.next()){
               String s1=rs.getString("DonorId");
               String s2=rs.getString("Name");
               String s3=rs.getString("Age");
               String s4=rs.getString("Gender");
               String s5=rs.getString("Bg");
               String s6=rs.getString("Id");
               String s7=rs.getString("Address");
               String s8=rs.getString("Contact");
               String s9=rs.getString("Added by");
               
               rowData[0]=s1;
               rowData[1]=s2;
               rowData[2]=s3;
               rowData[3]=s4;
               rowData[4]=s5;
               rowData[5]=s6;
               rowData[6]=s7;
               rowData[7]=s8;
               rowData[8]=s9;
               
               model.addRow(rowData);
           }
           
       }catch(Exception e){
            
       }
    }
    
    
    
    
    
    public void close(){
        WindowEvent winclose=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclose);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box;
    private javax.swing.JPasswordField cac;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable musertable;
    private javax.swing.JPasswordField nac;
    private javax.swing.JPasswordField pac;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTable table;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
